version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "1234:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./code:/code

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_ROOT_PASSWORD: 123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
      